/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String... args) {
        RestClient rest = new RestClient(args); 
        rest.gestorPeticiones();
    }
    
}
